modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"

[[mods]]
modId="better_silicon"
version="1.19.4-1.0.1"
displayName="Better Silicon"
logoFile="better_silicon.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Makes silicon much easier to attain for those mass-storage tech mods.
'''

[[dependencies.better_silicon]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_silicon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
