modLoader="javafml"
loaderVersion="[46,)"
license="GNU General Purpose License v3 (GPLv3)"

[[mods]]
modId="better_silicon"
version="1.20-1.1.7"
displayName="Better Silicon"
logoFile="better_silicon.png"
credits="Scalar Team"
authors="Lemon_Juiced"

description='''
Makes silicon much easier to attain for those mass-storage tech mods.
'''

[[dependencies.better_silicon]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.better_silicon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
